courses/urls.py
from django.conf.urls import url
from django.urls import path
from .views import CourseList, CourseDetail, CourseCreation, CourseUpdate, CourseDelete

app_name = 'courses'
urlpatterns = [
    path('', CourseList.as_view(), name='list'),
    path('<pk>', CourseDetail.as_view(), name='detail'),
    path('nuevo/', CourseCreation.as_view(), name='new'),
    path('editar/<pk>', CourseUpdate.as_view(), name='edit'),
    path('borrar/<pk>', CourseDelete.as_view(), name='delete'),

]

plat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('courses.urls')),
    path('admin/', admin.site.urls),
]

courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=140)
    start_date = models.CharField(max_length=140)
    end_date = models.CharField(max_length=140)
    picture = models.CharField(max_length=140)
    ola = models.CharField(max_length=140)

courses/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Course

# Create your views here.

class CourseList(ListView):
    model = Course
    template_name = 'courses/course_list.html'

class CourseDetail(DetailView):
    model = Course
    template_name = 'courses/course_detail.html'

class CourseCreation(CreateView):
    model = Course
    success_url = reverse_lazy('courses:list')
    fields = ['name', 'start_date', 'end_date', 'picture', 'ola']

class CourseUpdate(UpdateView):
    model = Course
    success_url = reverse_lazy('courses:list')
    fields = ['name', 'start_date', 'end_date', 'picture', 'ola']

class CourseDelete(DeleteView):
    model = Course
    template_name = 'courses/courseconfirmdelete.html'
    success_url = reverse_lazy('courses:list')

courses/templates/courses/course_detail.html
{%include 'courses/head.html' %}
<title>Curso ID {{course.pk}}</title>
<h1>{{ course.name }}</h1>
<p>Fecha de inicio: <i>{{ course.start_date }}</i></p>
<p>Fecha de fin: <i>{{ course.end_date }}</i></p>
<p>Ola: <i>{{ course.ola }}</i></p>
<p>
    <a href="{% url "courses:list" %}">Regresar</a>
</p>

courses/templates/courses/course_form.html
{%include 'courses/head.html' %}
<form method="post" class="crear">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Enviar" />
</form>

courses/templates/courses/course_list.html
{%include 'courses/head.html' %}
<h1 class="liscursos">Cursos</h1>

<p>
    <button class="bcurso" onclick="location.href='{% url 'courses:new' %}'" type="button">Crear curso</button>
</p>

<ul class="liscursos">
    {% for course in object_list %}
        <li>
            <p>{{ course.name }}</p>
            <p>
                <button class="bver" onclick="location.href='{% url 'courses:detail' course.id %}'" type="button">Ver</button>
                <button class="bver" onclick="location.href='{% url 'courses:edit' course.id %}'" type="button">Editar</button>
                <button class="bver" onclick="location.href='{% url 'courses:delete' course.id %}'" type="button">Borrar</button>
            </p>
        </li>
    {% endfor %}
</ul>

courses/templates/courses/courseconfirmdelete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

courses/templates/courses/head.html
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}"> 